### ISSUE TITLE
node-v6.10.0 版本无法使用

### ISSUE THREAD

**Issue by paddingme** [QingWei-Li/docsify#128] opened 2017-03-14 13:38 UTC
![image](https://cloud.githubusercontent.com/assets/5771087/23903240/cec201be-08fe-11e7-9b6b-48d774d1940c.png)

**Comment by jrappen** [comment] 2017-03-14 20:37
@paddingme please check if your issue is a duplicate of QingWei-Li/docsify-cli#9

**Comment by QingWei-Li** [comment] 2017-03-15 07:53
fixed in `v3.2.0` Thanks @jrappen

**Closed by QingWei-Li** 2017-03-15 07:53 UTC
