### ISSUE TITLE
BUG 4.6.8

### ISSUE THREAD

**Issue by willin** [QingWei-Li/docsify#434] opened 2018-03-23 03:08 UTC
4.6.7 OK

After 4.6.8 All images cannot show.

```
// folder/test.md
![](/static/1.png) 
=> 
<img src="/folder/static/1.png" />
```

**Comment by QingWei-Li** [comment] 2018-03-23 03:09
Duplicate of #415

**Closed by QingWei-Li** 2018-03-23 03:09 UTC
