### ISSUE TITLE
Inline file contents in directory

### ISSUE THREAD

**Issue by pnegahdar** [QingWei-Li/docsify#177] opened 2017-06-01 01:05 UTC
It would be cool to inline code snippets in the directory for example applications. Something like:

```python
{{ inline examples/quickstart/app.py }}
```

is there anyway to achieve this?

**Comment by QingWei-Li** [comment] 2017-06-01 01:58
Duplicate of lhttps://github.com/QingWei-Li/docsify/issues/134

But I have no idea yet. 🤷‍♀️

**Closed** 2017-06-23 09:11 UTC
Labels: duplicate
